require(ggmap)
require(readr)
require(dplyr)
require(maps)
require(mapdata)
iata <- read_csv("GlobalAirportDatabase.csv")
file2 <- read_csv("file.csv")
iata_min <- select(iata,IATA,Lat,Long)
orig_join <- inner_join(iata_min,file2,by=c("IATA"="Orig"))
